### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [joshwget/tc359-project17#1]
This is looking good, apart from a minor indentation issue in [`static_helper.rb`](https://github.com/joshwget/tc359-project17/blob/master/app/helpers/static_helper.rb). The standard indentation for Ruby (`.rb`) files is two-space soft-tabs rather than the 4 spaces here. And in Rails projects, it's actually best practice to have *every* file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use with that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by joshwget** [comment]
Not sure how that happened! I'm pretty sure my editor is set on two space. Just updated my .vimrc recently though, maybe I messed something up. Anyways, it should be fixed now.

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
